Repository Step3-kakao-tech-campus/Team9_BE, pull requests merged in 2023-09, with the labels that each got.

#9 Conf: Initial Project
  linknamu/.gitignore
  linknamu/build.gradle
  linknamu/gradle/wrapper/gradle-wrapper.jar
  linknamu/gradle/wrapper/gradle-wrapper.properties
  linknamu/gradlew
  linknamu/gradlew.bat
  linknamu/settings.gradle
  linknamu/src/main/java/com/kakao/linknamu/LinknamuApplication.java
  linknamu/src/main/resources/application.properties
  linknamu/src/test/java/com/kakao/linknamu/LinknamuApplicationTests.java
Labels: Priority: High, Domain: Environment

#13 ERD를 기반으로 JPA 엔티티 구현
  linknamu/src/main/java/com/kakao/linknamu/Bookmark/Bookmark.java
  linknamu/src/main/java/com/kakao/linknamu/Bookmark/BookmarkJPARepository.java
  linknamu/src/main/java/com/kakao/linknamu/BookmarkTag/BookmarkTagJPARepository.java
  linknamu/src/main/java/com/kakao/linknamu/BookmarkTag/Bookmark_Tag.java
  linknamu/src/main/java/com/kakao/linknamu/Category/Category.java
  linknamu/src/main/java/com/kakao/linknamu/Category/CategoryJPARepository.java
  linknamu/src/main/java/com/kakao/linknamu/Tag/Tag.java
  linknamu/src/main/java/com/kakao/linknamu/Tag/TagJPARepository.java
  linknamu/src/main/java/com/kakao/linknamu/User/User.java
  linknamu/src/main/java/com/kakao/linknamu/User/UserJPARepository.java
Labels: Priority: Medium, Status: In Progress, Domain: DB

#30 북마크 추가하기 API
  linknamu/src/main/java/com/kakao/linknamu/bookmark/BookmarkJPARepository.java
  linknamu/src/main/java/com/kakao/linknamu/bookmark/controller/BookmarkController.java
  linknamu/src/main/java/com/kakao/linknamu/bookmark/dto/BookmarkRequestDTO.java
  linknamu/src/main/java/com/kakao/linknamu/bookmark/entity/Bookmark.java
  linknamu/src/main/java/com/kakao/linknamu/bookmark/repository/BookmarkJPARepository.java
  linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkService.java
  linknamu/src/main/java/com/kakao/linknamu/bookmarkTag/BookmarkTag.java
  linknamu/src/main/java/com/kakao/linknamu/category/Category.java
  linknamu/src/main/java/com/kakao/linknamu/tag/TagJPARepository.java
  linknamu/src/main/java/com/kakao/linknamu/tag/entity/Tag.java
  linknamu/src/main/java/com/kakao/linknamu/tag/repository/TagJPARepository.java
Labels: Priority: High, Status: In Progress, Domain: API
